import os
import time
import numpy as np
import streamlit as st
import kagglehub

from keras.models import load_model
from keras.preprocessing import image

# -------------------------------
# Streamlit config
# -------------------------------
st.set_page_config(
    page_title="AI vs Human Image Detector",
    layout="centered"
)

# -------------------------------
# Sidebar
# -------------------------------
app_mode = st.sidebar.selectbox(
    "Select Page",
    ["Home", "Upload and Predict"]
)

# -------------------------------
# Load model (cached)
# -------------------------------
@st.cache_resource
def load_ai_model():
    model_dir = kagglehub.model_download(
        "utkarshsaxenadn/ai-vs-human/tensorflow2/default/1"
    )

    # Find the .keras file inside the directory
    model_path = None
    for file in os.listdir(model_dir):
        if file.endswith(".keras"):
            model_path = os.path.join(model_dir, file)
            break

    if model_path is None:
        raise FileNotFoundError("No .keras model file found in KaggleHub directory")

    model = load_model(model_path, compile=False)
    return model


model = load_ai_model()

# -------------------------------
# Home Page
# -------------------------------
if app_mode == "Home":
    st.title("AI vs Human Image Detector")
    st.write(
        """
        This application uses a deep learning model to determine whether
        an image was generated by **AI** or created by a **human**.

        **How it works:**
        - Upload an image
        - The model analyzes visual artifacts
        - You receive a prediction
        """
    )
    st.image("ai-human.jpg", caption="AI vs Human", use_container_width=True)

# -------------------------------
# Upload & Predict Page
# -------------------------------
elif app_mode == "Upload and Predict":
    st.subheader("Upload an Image")

    uploaded_file = st.file_uploader(
        "Choose an image file",
        type=["jpg", "jpeg", "png"]
    )

    if uploaded_file is not None:
        st.image(uploaded_file, caption="Uploaded Image", use_container_width=True)

        if st.button("Predict"):
            with st.spinner("Analyzing image..."):
                time.sleep(1)

                # Load and preprocess image
                img = image.load_img(uploaded_file, target_size=(512, 512))
                img_array = image.img_to_array(img) / 255.0
                img_array = np.expand_dims(img_array, axis=0)

                # Predict
                prediction = model.predict([img_array, img_array])

                confidence = float(prediction[0][0])

                if confidence > 0.5:
                    st.error(
                        f"🧠 **AI Generated Image**\n\nConfidence: {confidence:.2%}"
                    )
                else:
                    st.success(
                        f"🧑 **Human Generated Image**\n\nConfidence: {(1 - confidence):.2%}"
                    )





# import streamlit as st
# import tensorflow as tf
# from tensorflow.keras.models import load_model
# import numpy as np
# import pandas as pd
# import pickle  #to load a saved model
# import base64  #to open .gif files in streamlit app
# from tensorflow.keras.preprocessing import image
# import kagglehub
# import time
# from io import StringIO

# # @st.cache_data(suppress_st_warning=True)
# @st.cache_data
# def get_fvalue(val):    
# 	feature_dict = {"No":1,"Yes":2}    
# 	for key,value in feature_dict.items():        
# 		if val == key:            
# 			return value
# def get_value(val,my_dict):    
# 	for key,value in my_dict.items():        
# 		if val == key:            
# 			return value

# app_mode = st.sidebar.selectbox(':primary[Select Page]',['Home','Upload and Predict']) #two pages

# css="""
# <style>
#     [data-testid="stSidebar"] {
#         background: #524f4f;
#         # font-color: white;
#     }
# </style>
# """
# st.write(css, unsafe_allow_html=True)



# # Download latest version
# # path = kagglehub.model_download("utkarshsaxenadn/ai-vs-human/tensorFlow2/default")
# # path = kagglehub.model_download("utkarshsaxenadn/ai-vs-human/tensorflow2/default/1/ResNet50V2-AIvsHumanGenImages.keras")
# # path = kagglehub.model_download("utkarshsaxenadn/ai-vs-human/tensorflow2/default/1/ResNet152V2-AIvsHumanGenImages.keras")
# path = kagglehub.model_download("utkarshsaxenadn/ai-vs-human/tensorFlow2/default")

# # resnet152_model_path = '/kaggle/input/ai-vs-human/tensorflow2/default/1/ResNet152V2-AIvsHumanGenImages.keras'

# print("Path to downloaded model:", path)

# # Load the trained model (Use the single-input classifier version) :
# # path = path + "/1/ResNet50V2-AIvsHumanGenImages.keras"
# model = load_model(path, compile=False)

# if app_mode=='Home':   
#     st.title('Image Generated by AI or Human')
#     st.write("Upload images to determine if they are AI or Human generated images")
#     st.image('ai-human.jpg')    

# elif app_mode == 'Upload and Predict':     
# 	st.subheader('Is it an AI or Human generated image ?')    
# 	img_path = st.file_uploader("Please upload an image, wait a few seconds and click Predict")

# 	# Create a placeholder for the progress bar
# 	progress_placeholder = st.empty()
# 	status_placeholder = st.empty()

# 	if img_path is not None:
# 	    # Simulated processing with a progress bar
# 	    progress = progress_placeholder.progress(0)
# 	    # status_text = st.empty()

# 	    for percent_complete in range(100):
# 	        time.sleep(0.02)  # Simulate processing time
# 	        progress.progress(percent_complete + 1)
# 	        status_placeholder.text(f"Processing... {percent_complete + 1}%")
	    
# 	    progress_placeholder.empty()
# 	    status_placeholder.empty()

# 	if st.button("Predict"):
# 		# Create a placeholder for the progress bar
# 		progress_placeholder = st.empty()
# 		status_placeholder = st.empty()

# 		st.session_state.button = False
# 		img = image.load_img(img_path, target_size=(512, 512))  # ResNet50V2 input size
# 		img_array = image.img_to_array(img) / 255.0  # Normalize
# 		img_array = np.expand_dims(img_array, axis=0)  # Expand dims for batch processing

#                 # Predict
# 		prediction = model.predict(img_array)
		
# 		if prediction[0] > 0.5 :            
# 			st.error('This is an AI generated image')
# 			st.image(img_path, caption='AI generated image', use_container_width=True)
# 		elif prediction[0] <= .5 :
# 			st.success('This is a Human generated image')
# 			st.image(img_path, caption='Human generated image', use_container_width=True)
